### ISSUE TITLE
Real-world CPU synthetic benchmark as a supplementary side-goal?

### ISSUE THREAD

**Issue by Kein** [cmuratori/blandwidth#13]
Dont have to be priority, but it would be nice to have another tool that can be a groundbase benchmark for CPUs.

**Comment by cmuratori** [comment]
Not sure what you mean - do you mean just a generic benchmark like specint or something?

\- Casey

**Comment by Kein** [comment]
Generic, yes, but a little bit down the level, more akin to user-oriented benchmarks like Linpack is used to measure memory speed/bandwidth differences with different configurations.

**Comment by cmuratori** [comment]
That sounds like it should be a totally different utility, really.

\- Casey

**Comment by Kein** [comment]
Which is why I said as a supplementary goal. Dont have to change anything about the tool, but if you can snuck in option or two at the will that'd be nice.
